spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false

  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.globally_quoted_identifiers: false

server:
  port: 8080
